version: '3.4'

services:

  celery:
    build: 
      context: .
      dockerfile: DockerfileCelery
    restart: unless-stopped
    environment:
      - CELERY_URL=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis
    command: celery -A tasks worker --loglevel=INFO
  
  redis:
    restart: unless-stopped
    image: redis:5.0.4
    ports: 
      - 6379:6379
    command: redis-server

